# Site settings
title: Bioinformatics Workshops
email: turner@virginia.edu
github: stephenturner
twitter: genetics_blog
description: "Site description."
url: "http://stephenturner.us"
baseurl: ""

# Build settings
markdown: redcarpet
permalink: pretty
