# Site settings
title: Bioinformatics Workshops
email: turner@virginia.edu
github: stephenturner
twitter: genetics_blog
description: "Course materials and announcements for Stephen Turner's bioinformatics workshops."
url: "http://stephenturner.us"
baseurl: "/tmp"

# Build settings
markdown: redcarpet
permalink: pretty
