# Site settings
title: UVA Bioconnector Workshops
email: bioinformatics@virginia.edu
github: stephenturner
twitter: genetics_blog
description: "Course materials and announcements for Stephen Turner's bioinformatics workshops."
url: "http://stephenturner.us"

# See http://jekyllrb.com/docs/github-pages/#project-page-url-structure
# Use `jekyll serve --baseurl ''` to serve locally.
baseurl: "/workshops2015"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables", "no_intra_emphasis", "autolink", "footnotes"]
permalink: pretty
exclude: [pdf]
